// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://citcshcehztpbumkvywz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdGNzaGNlaHp0cGJ1bWt2eXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQzNzksImV4cCI6MjA2NTM0MDM3OX0.Doz0Hm-hbTZOgAyDR9s1JSnWmKuAZvlkIYwIsfpzXq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);